<style type="text/css">
    .bbs_footer_ownerinfo                               {width:100%; height:50px; background-color:#E8F3FD; border-top:1px solid #9DB3C5; clear:both;}
    .bbs_footer_ownerinfo .left                         {width:450px; height:50px; line-height:25px; text-align:left; color:#666666; margin-left:15px; float:left; }
    .bbs_footer_ownerinfo .right                        {width:450px; height:50px; line-height:25px; text-align:right; color:#666666; margin-right:15px; float:right; }
    
</style>

<div class="cell_h"></div>
<div class="bbs_footer_ownerinfo">
    <div class="left">
    关于我们　|　广告招商　|　举报中心　|　联系方式　|　客户服务　|　会员注册 <br/>
    Powered by mingrisoft.com
    </div>
    <div class="right">
        E-mail：mingrisoft@mingrisoft.com　电话：400-676-1066　吉ICP备07500273号<br/>
    Copyright&nbsp;&copy;&nbsp;吉林省明日科技有限公司&nbsp;1999-2009,&nbsp;&nbsp;All&nbsp;Rights&nbsp;Reserved
    </div>
</div>
