<style type="text/css">
    .userHeader_top                                     {width:100%; height:75px; background:url(<?php echo $this->baseUrl('/img/user_top_bg.gif')?>); clear:both;}
    .userHeader_top .dh                                 {width:760px; height:75px; clear:both;}
    .userHeader_top .dh .logo                           {width:230px; height:75px; background-color:#FFFFFF; float:left;}
         
    .userHeader_form                                    {width:700px; clear:both;}
    .userHeader_form .left                              {width:30px; height:300px; float:left; }  
    .userHeader_form .center                            {width:450px; height:300px; float:left; }  
    .userHeader_form .right                             {width:220px; height:300px; float:right; }  
      
 
    .userHeader_dh .li1                                 {width:80px; height:30px; line-height:30px; background-color:#ECECEC; float:left;} 
    .userHeader_dh .li2                                 {width:10px; height:30px; float:left;}
             
    .userHeader_form .center .label                     {width:480px; height:20px; line-height:20px; color:#006600; text-align:left; font-size:13px; clear:both; }
    .userHeader_form .center .field                     {width:480px; height:25px; line-height:25px; text-align:left; clear:both; }
    .userHeader_form .center .description               {width:480px; height:20px; line-height:20px; clear:both; }
     
</style>


<div class="cell_h"></div>
<div class="userHeader_top">
    <div class="dh">
        <div class="logo">
            <img src="<?php echo $this->baseUrl('/img/logo.jpg')?>" />
        </div>
    </div>
</div>
<div class="cell_h"></div>



